//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIDIApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        public string Discontinued { get; set; }
    }
}
